app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__, static_folder='../static')

from . import views

app/main/views.py
from flask import redirect, url_for, render_template
from flask.ext.login import current_user
from . import main


@main.route('/')
def index():
    return render_template("main/index.html")


@main.route('/statistics')
def statistics():
    return render_template("main/statistics.html")

app/templates/main/base.html
<!DOCTYPE html>
<html lang="zh-CN">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
    <meta name="description" content="">
    <meta name="author" content="">

    {% if title -%}
      <title>{{ title }} - CUIT 奖项管理</title>
    {%- else -%}
      <title>CUIT 奖项管理</title>
    {%- endif %}

    <link rel="stylesheet" href="{{ url_for('static', filename='plugins/Font-Awesome-4.4.0/css/font-awesome.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='bootstrap/css/bootstrap.min.css') }}"/>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="//cdn.bootcss.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="//cdn.bootcss.com/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

    <link rel="stylesheet" href="{{ url_for('static', filename='styles/index.css') }}">
    {% block head %}{% endblock %}
  </head>

  <body>
  <div class="navbar-wrapper">
      <div class="container">
    <nav class="navbar navbar-default">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">CUIT 奖项管理</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li><a href="{{ url_for('main.index') }}">主页</a></li>
            <li><a href="{{ url_for('main.statistics') }}">统计</a></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li><a href="{{ url_for('admin.index') }}"><span>管理员工作</span></a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>
      </div>
    </div>


    <div class="container">
      <div class="content">
        <h2>Content</h2>
        {% block content %}{% endblock %}
      </div>
    </div> <!-- /container -->

    <script src="{{ url_for('static', filename='plugins/jQuery/jQuery-1.11.3.min.js') }}"></script>
    <script src="{{ url_for('static', filename='bootstrap/js/bootstrap.min.js') }}"></script>
    {% block scripts %}{% endblock %}
  </body>
</html>

app/templates/main/index.html
<!DOCTYPE html>
<html lang="zh-CN">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
    <meta name="description" content="">
    <meta name="author" content="">

    <title>CUIT 奖项管理</title>

    <link rel="stylesheet" href="//cdn.bootcss.com/font-awesome/4.5.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{{ url_for('static', filename='bootstrap/css/bootstrap.min.css') }}"/>


    <!--[if lt IE 9]>
      <script src="//cdn.bootcss.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="//cdn.bootcss.com/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

    <!-- Custom styles for this template -->
    <link rel="stylesheet" href="{{ url_for('static', filename='styles/index.css') }}">
  </head>
<!-- NAVBAR
================================================== -->
  <body>
    <div class="navbar-wrapper">
      <div class="container">

        <nav class="navbar navbar-default navbar-static-top">
          <div class="container">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand" href="#">CUIT 奖项管理</a>
            </div>
            <div id="navbar" class="navbar-collapse collapse">
              <ul class="nav navbar-nav">
                <li class="active"><a href="#">主页</a></li>
                <li><a href="{{ url_for('main.statistics') }}">统计</a></li>
              </ul>
              <ul class="nav navbar-nav navbar-right">
                <li><a href="{{ url_for('admin.index') }}"><span>管理员工作</span></a></li>
              </ul>
            </div>
          </div>
        </nav>
{#        <div  class="panel panel-primary" style="float: left;width:88px;margin-top: 80px; margin-left:40px">#}
{#            <ul class="nav navbar-nav navbar-left">#}
{#                <li><a href="{{ url_for('admin.index') }}"><span>学生验证</span></a></li>#}
{#            </ul>#}
{#        </div>#}
      </div>
    </div>

    {# 图片轮播 #}
    <!-- Carousel
    ================================================== -->

{#    <div class="col-xs-8">#}
    <div id="myCarousel" class="carousel slide" data-ride="carousel">
      <!-- Indicators -->
        <ol class="carousel-indicators">
		<li data-target="#myCarousel" data-slide-to="0" class="active"></li>
		<li data-target="#myCarousel" data-slide-to="1"></li>
	</ol>
      <div class="carousel-inner" role="listbox">
          <div class="item active">
          <img class="first-slide" src="{{ url_for('static', filename='images/index-bg2.jpg') }}" alt="First slide">
          <div class="container">
            <div class="carousel-caption">
            </div>
          </div>
        </div>
          <div class="item">
          <img class="first-slide" src="{{ url_for('static', filename='images/index-bg.jpg') }}" alt="second slide">
          <div class="container">
            <div class="carousel-caption">
            </div>
          </div>
          </div>
      </div>
        <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left"></span>
        <span class="sr-only">Previous</span>
        </a>
        <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right"></span>
        <span class="sr-only">Next</span>
        </a>
    </div><!-- /.carousel -->
{#    </div>#}

    <!-- Marketing messaging and featurettes
    ================================================== -->
    <!-- Wrap the rest of the page in another container to center all the content. -->

    <div class="container">

      <!-- FOOTER -->
      <footer>
        <p class="pull-right"><a href="#">Back to top</a></p>
        <p>Copyright &copy; 2015 成都信息工程大学</p>
      </footer>

    </div><!-- /.container -->


    <script src="{{ url_for('static', filename='plugins/jQuery/jQuery-1.11.3.min.js') }}"></script>
    <script src="{{ url_for('static', filename='bootstrap/js/bootstrap.min.js') }}"></script>
    <script src="{{ url_for('static', filename='bootstrap/css/bootstrap.min.css') }}"></script>

  </body>
</html>

app/templates/main/statistics.html
{% extends "main/base.html" %}